#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-highline
Version  : 1.7.2
Release  : 6
URL      : https://rubygems.org/downloads/highline-1.7.2.gem
Source0  : https://rubygems.org/downloads/highline-1.7.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-code_statistics
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rubygems-tasks
BuildRequires : rubygem-test-unit

%description
= HighLine
by James Edward Gray II
{<img src="https://travis-ci.org/JEG2/highline.svg" alt="Build Status" />}[https://travis-ci.org/JEG2/highline]
{<img src="https://img.shields.io/gem/v/highline.svg?style=flat" />}[http://rubygems.org/gems/highline]

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n highline-1.7.2
gem spec %{SOURCE0} -l --ruby > rubygem-highline.gemspec

%build
gem build rubygem-highline.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
highline-1.7.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=intel.com,localhost
pushd %{buildroot}%{gem_dir}/gems/highline-1.7.2
rake --trace test TESTOPTS="-v"
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/highline-1.7.2.gem
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/ColorScheme/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/ColorScheme/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/ColorScheme/cdesc-ColorScheme.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/ColorScheme/definition-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/ColorScheme/include%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/ColorScheme/keys-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/ColorScheme/load_from_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/ColorScheme/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/ColorScheme/to_constant-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/ColorScheme/to_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/ColorScheme/to_symbol-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/HighLine/HighLine/String/cdesc-String.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/HighLine/HighLine/cdesc-HighLine.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/HighLine/cdesc-HighLine.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/cdesc-Menu.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/choice-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/choices-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/flow-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/header-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/help-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/hidden-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/index%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/index-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/index_suffix-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/init_help-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/layout%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/layout-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/list_option-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/nil_on_handled-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/prompt-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/select-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/select_by-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/shell-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/to_ary-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Menu/update_responses-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/NoAutoCompleteMatch/cdesc-NoAutoCompleteMatch.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/above-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/answer_or_default-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/answer_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/append_default-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/below-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/build_responses-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/case-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/cdesc-Question.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/change_case-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/character-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/completion-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/confirm-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/default-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/directory-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/echo-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/expected_range-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/first_answer%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/first_answer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/gather-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/glob-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/in-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/in_range%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/limit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/overwrite-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/question-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/readline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/remove_whitespace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/responses-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/selection-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/valid_answer%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/validate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/verify_match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Question/whitespace-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/QuestionError/cdesc-QuestionError.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/SampleColorScheme/cdesc-SampleColorScheme.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/SampleColorScheme/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Simulate/cdesc-Simulate.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Simulate/eof%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Simulate/getbyte-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Simulate/gets-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Simulate/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Simulate/with-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/String-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/StringExtensions/cdesc-StringExtensions.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/StringExtensions/color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/StringExtensions/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/StringExtensions/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/StringExtensions/on-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/StringExtensions/on_rgb-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/StringExtensions/rgb-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/StringExtensions/uncolor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/ansi_rgb_to_hex-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/blue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/bright-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/builtin-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/cdesc-Style.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/code_index-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/create_bright_variant-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/dup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/find_style-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/green-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/index-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/light-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/list-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/on-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/red-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/rgb-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/rgb-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/rgb_hex-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/rgb_number-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/rgb_parts-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/to_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/uncolor-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/Style/variant-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/SystemExtensions/WinAPI/DL/cdesc-DL.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/SystemExtensions/WinAPI/GetConsoleScreenBufferInfo-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/SystemExtensions/WinAPI/GetStdHandle-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/SystemExtensions/WinAPI/_getch-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/SystemExtensions/WinAPI/cdesc-WinAPI.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/SystemExtensions/cdesc-SystemExtensions.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/SystemExtensions/get_character-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/SystemExtensions/initialize_system_extensions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/SystemExtensions/raw_no_echo_mode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/SystemExtensions/restore_mode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/SystemExtensions/terminal_size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/actual_length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/agree-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/ask-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/cdesc-HighLine.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/choose-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/color-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/color_code-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/color_code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/color_scheme%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/color_scheme-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/colorize_strings-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/const_missing-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/continue_paging%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/explain_error-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/format_statement-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/gather-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/get_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/get_response-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/indent-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/indent_level-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/indent_size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/indentation-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/multi_indent-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/newline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/output_cols-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/output_rows-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/page_at%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/page_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/page_print-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/say-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/supports_rgb_color%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/track_eof%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/track_eof%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/uncolor-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/uncolor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/unique_answers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/use_color%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/use_color%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/using_color_scheme%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/wrap-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/wrap_at%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/HighLine/wrap_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/IO/cdesc-IO.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/Kernel/cdesc-Kernel.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/Object/or_ask-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/String/cdesc-String.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/StringIO/cdesc-StringIO.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/page-Changelog_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/page-INSTALL.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/page-LICENSE.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/highline-1.7.2/ri/page-TODO.ri
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/AUTHORS
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/COPYING
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/Changelog.md
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/INSTALL
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/TODO
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/doc/.cvsignore
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/examples/ansi_colors.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/examples/asking_for_arrays.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/examples/basic_usage.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/examples/color_scheme.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/examples/get_character.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/examples/limit.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/examples/menus.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/examples/overwrite.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/examples/page_and_wrap.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/examples/password.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/examples/repeat_entry.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/examples/trapping_eof.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/examples/using_readline.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/highline.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/lib/highline.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/lib/highline/color_scheme.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/lib/highline/compatibility.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/lib/highline/import.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/lib/highline/menu.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/lib/highline/question.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/lib/highline/simulate.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/lib/highline/string_extensions.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/lib/highline/style.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/lib/highline/system_extensions.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/lib/highline/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/setup.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/site/.cvsignore
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/site/highline.css
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/site/images/logo.png
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/site/index.html
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/test/string_methods.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/test/tc_color_scheme.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/test/tc_highline.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/test/tc_import.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/test/tc_menu.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/test/tc_string_extension.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/test/tc_string_highline.rb
/usr/lib64/ruby/gems/2.2.0/gems/highline-1.7.2/test/tc_style.rb
/usr/lib64/ruby/gems/2.2.0/specifications/highline-1.7.2.gemspec
