#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-highline
Version  : 1.7.8
Release  : 9
URL      : https://rubygems.org/downloads/highline-1.7.8.gem
Source0  : https://rubygems.org/downloads/highline-1.7.8.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : ruby
BuildRequires : rubygem-code_statistics
BuildRequires : rubygem-rdoc

%description
= HighLine
by James Edward Gray II
{<img src="https://travis-ci.org/JEG2/highline.svg" alt="Build Status" />}[https://travis-ci.org/JEG2/highline]
{<img src="https://img.shields.io/gem/v/highline.svg?style=flat" />}[http://rubygems.org/gems/highline]

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n highline-1.7.8
gem spec %{SOURCE0} -l --ruby > rubygem-highline.gemspec

%build
gem build rubygem-highline.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
highline-1.7.8.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/highline-1.7.8
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/highline-1.7.8.gem
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/AUTHORS
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/COPYING
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/Changelog.md
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/INSTALL
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/TODO
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/doc/.cvsignore
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/examples/ansi_colors.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/examples/asking_for_arrays.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/examples/basic_usage.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/examples/color_scheme.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/examples/get_character.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/examples/limit.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/examples/menus.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/examples/overwrite.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/examples/page_and_wrap.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/examples/password.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/examples/repeat_entry.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/examples/trapping_eof.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/examples/using_readline.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/highline.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline/color_scheme.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline/compatibility.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline/import.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline/menu.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline/question.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline/simulate.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline/string_extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline/style.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline/system_extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/setup.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/site/.cvsignore
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/site/highline.css
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/site/images/logo.png
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/site/index.html
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/test/string_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/test/tc_color_scheme.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/test/tc_highline.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/test/tc_import.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/test/tc_menu.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/test/tc_simulator.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/test/tc_string_extension.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/test/tc_string_highline.rb
/usr/lib64/ruby/gems/2.3.0/gems/highline-1.7.8/test/tc_style.rb
/usr/lib64/ruby/gems/2.3.0/specifications/highline-1.7.8.gemspec
